# -*- coding: utf-8 -*-
"""Pros and cons

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_HjWssHSszn39CyqSWObrsyQOpjhsAYc
"""

!pip install transformers torch pandas
from transformers import pipeline
import pandas as pd

#Load sentiment analysis model
sentiment=pipeline("sentiment-analysis")
#sample product review (you can change only this text later)
reviews="""The laptop starts quickly and works smoothly for daily tasks.
The screen quality is clear and good for watching videos.
Battery backup is average and needs charging often.
The  fans makes noise when many apps are running.
Overall it is a good laptop for students but not for gaming
"""
#Split review into sentences
sentences=reviews.split(".")
pros=[]
cons=[]
for s in sentences:
    s=s.strip()
    if s== "":
        continue
    result=sentiment(s)[0]
    if result["label"]=="POSITIVE":
         pros.append(s)
    elif result["label"]=="NEGATIVE":
        cons.append(s)
#Take only 2 pros and 2 cons
pros=pros[:2]
cons=cons[:2]
#Create Table
df=pd.DataFrame({
"Pros":pros,
"Cons":cons
})

df