# -*- coding: utf-8 -*-
"""Sentence similarity project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iOD0ydxMqNkf3mL3Yqs8IyLHEYyx3Z5O
"""

!pip install sentence-transformers

from sentence_transformers import SentenceTransformer,util

#load the model
model=SentenceTransformer('all-MiniLM-L6-v2')

#Take input from the user
text1=input("Enter the Text 1:")
text2=input("Enter the Text 2:")

#Convert text to embeddings
embedding1=model.encode(text1)
embedding2=model.encode(text2)

#Calculate Similarity
Similarity=util.cos_sim(embedding1,embedding2)

#Show result
print("\nSimilarity score:",round(float(Similarity),2))
if Similarity>0.75:
   print("Similarity level:High")
elif Similarity>0.4:
   print("Similarity level:Medium")
else:
   print("Similarity level:low")